import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'
import JotaiProvider from '@/components/providers/jotai-provicer'
import ChatLayout from '@/components/chat/chat-layout'
import SupabaseProvider from '@/components/providers/supabase-provider'
import SupabaseAuthProvider from '@/components/providers/supabase-auth-provider'
import { createClient } from '@/lib/supabase/server'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  const cookie= cookies()
  const supabase = createClient(cookie);
  const {
    data: { session },
  } = await supabase.auth.getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <JotaiProvider>
            <SupabaseAuthProvider serverSession={session}>
              <ThemeProvider>
                <ChatLayout>
                  {children}</ChatLayout>
              </ThemeProvider></SupabaseAuthProvider>
          </JotaiProvider></SupabaseProvider>
      </body>
    </html>
  )
}
